analytics: {}
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 1
  lightness: 0.703828
  rhythmicContrast: 0.944819
  saturation: 0.849758
cta: {}
layout_spectrum: 0.193693
name: johansetiawan
opengraph: {}
purpose: {}
typography_spectrum: 0.21338866111475274
